# Generated by Django 5.2.6 on 2025-10-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_pwa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='recipient_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='signature_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
