# Generated by Django 5.2.6 on 2025-10-28 18:32

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_pwa', '0002_deliveryrequest_recipient_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('availability', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('ON_DELIVERY', 'On Delivery')], default='OFFLINE', max_length=20)),
                ('driver_license_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='License number must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9-]+$')])),
                ('license_expiry_date', models.DateField()),
                ('license_document', models.FileField(blank=True, upload_to='delivery_drivers/licenses/')),
                ('national_id', models.FileField(blank=True, upload_to='delivery_drivers/national_ids/')),
                ('proof_of_address', models.FileField(blank=True, upload_to='delivery_drivers/proof_of_address/')),
                ('background_check_document', models.FileField(blank=True, upload_to='delivery_drivers/background_checks/')),
                ('profile_photo', models.ImageField(blank=True, upload_to='delivery_drivers/photos/')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_deliveries', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('mobile_money_number', models.CharField(blank=True, max_length=20)),
                ('mobile_money_provider', models.CharField(blank=True, help_text='e.g., MTN, Vodafone, AirtelTigo', max_length=50)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Driver Profile',
                'verbose_name_plural': 'Delivery Driver Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('driver_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Card'), ('BANK_TRANSFER', 'Bank Transfer')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='express_pwa.deliveryrequest')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_payments_received', to='express_pwa.deliverydriverprofile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Payment',
                'verbose_name_plural': 'Delivery Payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('BIKE', 'Motorcycle/Bike'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck')], default='BIKE', max_length=20)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2030)])),
                ('color', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('vin_number', models.CharField(blank=True, max_length=50, verbose_name='VIN Number')),
                ('registration_document', models.FileField(blank=True, upload_to='delivery_vehicles/registration/')),
                ('insurance_document', models.FileField(blank=True, upload_to='delivery_vehicles/insurance/')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('road_worthiness_document', models.FileField(blank=True, upload_to='delivery_vehicles/road_worthiness/')),
                ('road_worthiness_expiry_date', models.DateField(blank=True, null=True)),
                ('photo_front', models.ImageField(blank=True, upload_to='delivery_vehicles/photos/front/')),
                ('photo_back', models.ImageField(blank=True, upload_to='delivery_vehicles/photos/back/')),
                ('photo_side', models.ImageField(blank=True, upload_to='delivery_vehicles/photos/side/')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair')], default='GOOD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum weight capacity in kg', max_digits=6)),
                ('max_dimensions', models.CharField(blank=True, help_text='e.g., 100x80x60 cm', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='express_pwa.deliverydriverprofile')),
            ],
            options={
                'verbose_name': 'Delivery Vehicle',
                'verbose_name_plural': 'Delivery Vehicles',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
