# Generated by Django 5.2.6 on 2025-10-30 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('express_pwa', '0003_deliverydriverprofile_deliverypayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short code for the area', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Area',
                'verbose_name_plural': 'Delivery Areas',
                'ordering': ['region__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code for the region (e.g., ACC, KSI)', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Region',
                'verbose_name_plural': 'Delivery Regions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_deliveries', to='express_pwa.deliveryarea'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_deliveries', to='express_pwa.deliveryarea'),
        ),
        migrations.AddField(
            model_name='deliveryarea',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='express_pwa.deliveryregion'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_deliveries', to='express_pwa.deliveryregion'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_deliveries', to='express_pwa.deliveryregion'),
        ),
        migrations.AlterUniqueTogether(
            name='deliveryarea',
            unique_together={('region', 'code'), ('region', 'name')},
        ),
    ]
