# Generated by Django 4.2.26 on 2025-12-17 06:08

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('express_pwa', '0004_deliveryarea_deliveryregion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Assignment'), ('assigned', 'Assigned to Driver'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('special_instructions', models.TextField(blank=True, help_text='Special instructions for the entire order')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_express_orders', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='express_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Express Order',
                'verbose_name_plural': 'Express Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpressOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('package_type', models.CharField(choices=[('document', 'Document'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food Items'), ('fragile', 'Fragile Items'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('value', models.DecimalField(decimal_places=2, help_text='Declared value in GHS', max_digits=10)),
                ('urgency', models.CharField(choices=[('standard', 'Standard (24-48 hours)'), ('express', 'Express (Same day)'), ('urgent', 'Urgent (2-4 hours)')], default='standard', max_length=20)),
                ('pickup_address', models.TextField()),
                ('pickup_landmark', models.CharField(blank=True, max_length=200)),
                ('pickup_instructions', models.TextField(blank=True)),
                ('delivery_address', models.TextField()),
                ('delivery_landmark', models.CharField(blank=True, max_length=200)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Driver'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('recipient_signature', models.TextField(blank=True, help_text='Base64 encoded signature image')),
                ('signature_date', models.DateTimeField(blank=True, null=True)),
                ('signed_by_name', models.CharField(blank=True, max_length=100)),
                ('delivery_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_order_items', to='express_pwa.deliveryarea')),
                ('delivery_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_order_items', to='express_pwa.deliveryregion')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='express_pwa.expressorder')),
                ('pickup_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_order_items', to='express_pwa.deliveryarea')),
                ('pickup_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_order_items', to='express_pwa.deliveryregion')),
            ],
            options={
                'verbose_name': 'Express Order Item',
                'verbose_name_plural': 'Express Order Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
