# Generated by Django 4.2.26 on 2025-12-17 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('express_pwa', '0005_expressorder_expressorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='related_order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_request', to='express_pwa.expressorderitem'),
        ),
    ]
