# Generated by Django 5.2.6 on 2025-10-06 01:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license_number', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='License number must contain only uppercase letters, numbers, and hyphens', regex='^[A-Z0-9-]+$')])),
                ('license_expiry_date', models.DateField()),
                ('license_document', models.FileField(help_text="Upload driver's license (PDF or Image)", upload_to='ride/driver_documents/licenses/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='ride/driver_photos/')),
                ('national_id', models.FileField(help_text='National ID or Passport', upload_to='ride/driver_documents/ids/')),
                ('proof_of_address', models.FileField(blank=True, null=True, upload_to='ride/driver_documents/addresses/')),
                ('background_check_document', models.FileField(blank=True, null=True, upload_to='ride/driver_documents/background_checks/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('availability', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('ON_RIDE', 'On Ride')], default='OFFLINE', max_length=20)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Current latitude coordinate', max_digits=10, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Current longitude coordinate', max_digits=11, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder_name', models.CharField(blank=True, max_length=100)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pickup_address', models.CharField(max_length=500)),
                ('pickup_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dropoff_address', models.CharField(max_length=500)),
                ('dropoff_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dropoff_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('passenger_count', models.PositiveIntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests from passenger')),
                ('status', models.CharField(choices=[('REQUESTED', 'Ride Requested'), ('ACCEPTED', 'Driver Accepted'), ('DRIVER_ARRIVED', 'Driver Arrived'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED_BY_PASSENGER', 'Cancelled by Passenger'), ('CANCELLED_BY_DRIVER', 'Cancelled by Driver')], default='REQUESTED', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('driver_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('estimated_distance_km', models.DecimalField(decimal_places=2, help_text='Estimated distance in kilometers', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Actual distance traveled', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_duration_minutes', models.PositiveIntegerField(help_text='Estimated duration in minutes')),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Actual duration in minutes', null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('distance_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('time_fare', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Surge pricing multiplier', max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('WALLET', 'Wallet')], default='CASH', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_rides', to='ride.driverprofile')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ride',
                'verbose_name_plural': 'Rides',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('PASSENGER_TO_DRIVER', 'Passenger Rating Driver'), ('DRIVER_TO_PASSENGER', 'Driver Rating Passenger')], max_length=30)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional written review')),
                ('cleanliness_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('driving_rating', models.PositiveIntegerField(blank=True, help_text='Only for driver ratings', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rated_driver', models.ForeignKey(blank=True, help_text='Driver being rated (if rating type is passenger to driver)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='ride.driverprofile')),
                ('rated_user', models.ForeignKey(blank=True, help_text='User being rated (if rating type is driver to passenger)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ride.ride')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('RIDE_PAYMENT', 'Ride Payment'), ('REFUND', 'Refund'), ('DRIVER_PAYOUT', 'Driver Payout')], default='RIDE_PAYMENT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('driver_payout', models.DecimalField(decimal_places=2, help_text='Amount paid to driver after commission', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MOBILE_MONEY', 'Mobile Money'), ('WALLET', 'Wallet')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('external_transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=100)),
                ('payment_gateway_response', models.JSONField(blank=True, help_text='Raw response from payment gateway', null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='ride.driverprofile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='ride.ride')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='RideTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, help_text='Speed in km/h', max_digits=5, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, help_text='Direction in degrees (0-360)', max_digits=5, null=True)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_points', to='ride.ride')),
            ],
            options={
                'verbose_name': 'Ride Tracking Point',
                'verbose_name_plural': 'Ride Tracking Points',
                'ordering': ['ride', 'recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='e.g., Toyota, Honda', max_length=50)),
                ('model', models.CharField(help_text='e.g., Camry, Civic', max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)])),
                ('color', models.CharField(max_length=30)),
                ('license_plate', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='License plate must contain only uppercase letters, numbers, hyphens, and spaces', regex='^[A-Z0-9-\\s]+$')])),
                ('vin_number', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True)),
                ('registration_document', models.FileField(upload_to='ride/vehicle_documents/registrations/')),
                ('insurance_document', models.FileField(upload_to='ride/vehicle_documents/insurance/')),
                ('insurance_expiry_date', models.DateField()),
                ('road_worthiness_certificate', models.FileField(blank=True, null=True, upload_to='ride/vehicle_documents/roadworthiness/')),
                ('roadworthiness_expiry_date', models.DateField(blank=True, null=True)),
                ('front_photo', models.ImageField(blank=True, null=True, upload_to='ride/vehicle_photos/front/')),
                ('back_photo', models.ImageField(blank=True, null=True, upload_to='ride/vehicle_photos/back/')),
                ('side_photo', models.ImageField(blank=True, null=True, upload_to='ride/vehicle_photos/side/')),
                ('interior_photo', models.ImageField(blank=True, null=True, upload_to='ride/vehicle_photos/interior/')),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair')], default='GOOD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary vehicle used by driver')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='ride.driverprofile')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='ride.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('BIKE', 'Bike/Motorcycle'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('TRICYCLE', 'Tricycle')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('base_fare', models.DecimalField(decimal_places=2, help_text='Base fare for this vehicle category', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_km', models.DecimalField(decimal_places=2, help_text='Price per kilometer', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_per_minute', models.DecimalField(decimal_places=2, help_text='Price per minute (for wait time)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('max_passengers', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='ride/vehicle_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Category',
                'verbose_name_plural': 'Vehicle Categories',
                'ordering': ['vehicle_type', 'name'],
                'indexes': [models.Index(fields=['vehicle_type', 'is_active'], name='ride_vehicl_vehicle_df797a_idx')],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='ride.vehiclecategory'),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rides', to='ride.vehiclecategory'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['status', 'availability'], name='ride_driver_status_63b916_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['current_latitude', 'current_longitude'], name='ride_driver_current_1bdbde_idx'),
        ),
        migrations.AddIndex(
            model_name='driverprofile',
            index=models.Index(fields=['average_rating'], name='ride_driver_average_47c8d4_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_driver', 'rating'], name='ride_rating_rated_d_091f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user', 'rating'], name='ride_rating_rated_u_217754_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating_type', 'created_at'], name='ride_rating_rating__a409fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('ride', 'rating_type')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_id'], name='ride_paymen_payment_e970f2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['ride', 'status'], name='ride_paymen_ride_id_530cda_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer', 'status'], name='ride_paymen_payer_i_de6af9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_reference'], name='ride_paymen_transac_d4e7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'initiated_at'], name='ride_paymen_status_25e185_idx'),
        ),
        migrations.AddIndex(
            model_name='ridetracking',
            index=models.Index(fields=['ride', 'recorded_at'], name='ride_ridetr_ride_id_6952f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ridetracking',
            index=models.Index(fields=['latitude', 'longitude'], name='ride_ridetr_latitud_88d4fc_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_active', 'is_primary'], name='ride_vehicl_driver__04e661_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='ride_vehicl_license_9f7fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['passenger', 'status'], name='ride_ride_passeng_df72c3_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='ride_ride_driver__7e0995_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status', 'requested_at'], name='ride_ride_status_f18ce2_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['ride_id'], name='ride_ride_ride_id_3459df_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['payment_status'], name='ride_ride_payment_00a61e_idx'),
        ),
    ]
