# Generated by Django 5.2.6 on 2025-10-20 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Optional written review'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='cancellation_reason',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_requests',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Any special requests from passenger'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
