# Generated by Django 5.2.6 on 2025-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_payment_failure_reason_alter_rating_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='driver_completed',
            field=models.BooleanField(default=False, help_text='Driver marked ride as complete'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_completed',
            field=models.BooleanField(default=False, help_text='Passenger marked ride as complete'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passenger_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
