# Generated by Django 4.2.26 on 2025-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_driver_completed_ride_driver_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, help_text='Optional written review'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='special_requests',
            field=models.TextField(blank=True, help_text='Any special requests from passenger'),
        ),
        migrations.AlterField(
            model_name='vehiclecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
