# Generated by Django 5.2.6 on 2025-10-18 05:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='furnished',
            field=models.BooleanField(default=False, help_text='Is the property furnished?'),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_terms',
            field=models.TextField(blank=True, help_text='Additional lease terms and conditions (e.g., maintenance responsibilities, renewal terms)'),
        ),
        migrations.AddField(
            model_name='property',
            name='minimum_rental_years',
            field=models.IntegerField(default=1, help_text='Minimum number of years property must be rented for (1-10 years)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='property',
            name='pets_allowed',
            field=models.BooleanField(default=False, help_text='Are pets allowed in this property?'),
        ),
        migrations.AddField(
            model_name='property',
            name='utilities_included',
            field=models.BooleanField(default=False, help_text='Are utilities (water, electricity, etc.) included in rent?'),
        ),
        migrations.AddField(
            model_name='rentalbooking',
            name='rental_years',
            field=models.IntegerField(default=1, help_text='Number of years for property rental (1-10 years)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='RentalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('property', 'Property'), ('equipment', 'Equipment')], max_length=10)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rent.equipment')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rent.property')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rental_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_rental_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
