# Generated by Django 5.2.6 on 2025-10-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_savedequipment_savedproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(blank=True, default=1, help_text='Google Drive image link', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(help_text='Google Drive image link', max_length=500),
        ),
    ]
