# Generated by Django 5.2.6 on 2025-10-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_alter_property_main_image_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='main_image',
            field=models.URLField(blank=True, default='', help_text='Google Drive image link', max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.URLField(default='', help_text='Google Drive image link', max_length=500),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(blank=True, default='', help_text='Google Drive image link', max_length=500),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.URLField(default='', help_text='Google Drive image link', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.URLField(blank=True, default='', help_text='Google Drive image link', max_length=500),
        ),
    ]
