# Generated by Django 5.2.6 on 2025-10-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_alter_equipment_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(help_text='Google Drive image link (Required)', max_length=500),
        ),
    ]
