# Generated by Django 5.2.6 on 2025-10-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_property_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.URLField(help_text="Google Drive image link (Required). IMPORTANT: Set file sharing to 'Anyone with the link can view' in Google Drive", max_length=500),
        ),
    ]
