# Generated by Django 5.2.6 on 2025-10-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_alter_property_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='listing_type',
            field=models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale')], default='for_rent', help_text='Whether this equipment is for rent or for sale', max_length=10),
        ),
    ]
