# Generated by Django 5.2.6 on 2025-10-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_equipment_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='transaction_type',
            field=models.CharField(choices=[('rental', 'Rental'), ('purchase', 'Purchase')], default='rental', help_text='Whether this is a rental or purchase', max_length=10),
        ),
    ]
