# Generated by Django 5.2.6 on 2025-10-20 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0009_rentalbooking_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specifications',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Technical specifications'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Comma-separated amenities (e.g., Parking, WiFi, AC)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_terms',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Additional lease terms and conditions (e.g., maintenance responsibilities, renewal terms)'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Special requests or notes'),
        ),
        migrations.AlterField(
            model_name='rentalmessage',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='rentalreview',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Comma-separated amenities (e.g., AC, WiFi, Balcony)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
