# Generated by Django 5.2.6 on 2025-10-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalbooking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], default='cash', help_text='Payment method chosen by renter', max_length=10),
        ),
    ]
