# Generated by Django 4.2.26 on 2025-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0011_rentalbooking_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Main item image', null=True, upload_to='rental_items/'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='specifications',
            field=models.TextField(blank=True, help_text='Technical specifications'),
        ),
        migrations.AlterField(
            model_name='equipmentcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipmentimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Equipment image', null=True, upload_to='equipment_images/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities (e.g., Parking, WiFi, AC)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_terms',
            field=models.TextField(blank=True, help_text='Additional lease terms and conditions (e.g., maintenance responsibilities, renewal terms)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_image',
            field=models.ImageField(help_text='Main property image (Required)', upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Property image', null=True, upload_to='property_images/'),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='notes',
            field=models.TextField(blank=True, help_text='Special requests or notes'),
        ),
        migrations.AlterField(
            model_name='rentalmessage',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rentalreview',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities (e.g., AC, WiFi, Balcony)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Property image', null=True, upload_to='property_images/'),
        ),
    ]
