# Generated by Django 4.2.26 on 2025-12-20 20:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0012_alter_equipment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='room',
            name='property',
        ),
        migrations.AlterUniqueTogether(
            name='savedproperty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='property',
        ),
        migrations.RemoveField(
            model_name='savedproperty',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentalbooking',
            name='rental_years',
        ),
        migrations.RemoveField(
            model_name='rentalmessage',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='rentalmessage',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentalreview',
            name='property',
        ),
        migrations.RemoveField(
            model_name='rentalreview',
            name='review_type',
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated amenities (e.g., Parking, WiFi, AC)'),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='main_image',
            field=models.ImageField(default=1, help_text='Main property image (Required)', upload_to='properties/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentcategory',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rent.equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalbooking',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Number of items to rent', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rentalmessage',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rent.equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rentalreview',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rent.equipment'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyCategory',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='SavedProperty',
        ),
    ]
