# Generated by Django 5.2.6 on 2025-10-20 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='active_ingredients',
            field=ckeditor.fields.RichTextField(help_text='List of active ingredients'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='side_effects',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Possible side effects'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='storage_instructions',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Storage requirements'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='usage',
            field=ckeditor.fields.RichTextField(help_text='How to use this medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='warnings',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Warnings and contraindications'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Additional notes from patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacist_notes',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Notes from pharmacist/reviewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
