# Generated by Django 5.2.6 on 2025-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_medicine_active_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.URLField(blank=True, help_text='Direct image URL from any image hosting service', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_2',
            field=models.URLField(blank=True, help_text='Direct image URL from any image hosting service', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_3',
            field=models.URLField(blank=True, help_text='Direct image URL from any image hosting service', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='icon',
            field=models.URLField(blank=True, help_text='Direct icon URL from any image hosting service', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_1',
            field=models.URLField(blank=True, help_text='Direct image URL from any image hosting service', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_2',
            field=models.URLField(blank=True, help_text='Direct image URL from any image hosting service', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_3',
            field=models.URLField(blank=True, help_text='Direct image URL from any image hosting service', max_length=500, null=True),
        ),
    ]
