# Generated by Django 5.2.6 on 2025-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_medicine_image_alter_medicine_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
