# Generated by Django 4.2.26 on 2025-12-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_prescription_doctor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='active_ingredients',
            field=models.TextField(help_text='List of active ingredients'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image',
            field=models.ImageField(blank=True, help_text='Main medicine image', null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Additional medicine image', null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Additional medicine image', null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Possible side effects'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='storage_instructions',
            field=models.TextField(blank=True, help_text='Storage requirements'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='usage',
            field=models.TextField(help_text='How to use this medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='warnings',
            field=models.TextField(blank=True, help_text='Warnings and contraindications'),
        ),
        migrations.AlterField(
            model_name='medicinecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_notes',
            field=models.TextField(blank=True, help_text='Additional notes from patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pharmacist_notes',
            field=models.TextField(blank=True, help_text='Notes from pharmacist/reviewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Review image', null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Additional medicine image', null=True, upload_to='medicines/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Additional medicine image', null=True, upload_to='medicines/'),
        ),
    ]
