# Generated by Django 4.2.26 on 2026-01-13 05:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0005_alter_medicine_active_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Pharmacy logo image', null=True, upload_to='pharmacies/logos/')),
                ('image', models.ImageField(blank=True, help_text='Main pharmacy image', null=True, upload_to='pharmacies/images/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map location', max_digits=9, null=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(choices=[('retail', 'Retail Pharmacy'), ('hospital', 'Hospital Pharmacy'), ('community', 'Community Pharmacy'), ('online', 'Online Pharmacy'), ('compounding', 'Compounding Pharmacy')], default='retail', max_length=20)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Pharmacy verification status')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], default='pending_verification', max_length=25)),
                ('is_featured', models.BooleanField(default=False)),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours text (e.g., "Mon-Fri: 8AM-9PM, Sat: 9AM-6PM")')),
                ('is_24_hours', models.BooleanField(default=False)),
                ('delivery_available', models.BooleanField(default=True)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('free_delivery_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Order amount above which delivery is free', max_digits=10, null=True)),
                ('estimated_delivery_time', models.PositiveIntegerField(default=60, help_text='Estimated delivery time in minutes')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Pharmacy owner/manager', on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy',
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='The pharmacy that sells this medicine', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='pharmacy.pharmacy'),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(blank=True, help_text='The pharmacy fulfilling this order', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pharmacy.pharmacy'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['slug'], name='pharmacy_ph_slug_5dfd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['city', 'status'], name='pharmacy_ph_city_50c5fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['owner'], name='pharmacy_ph_owner_i_a034fd_idx'),
        ),
    ]
