# Generated by Django 5.2.6 on 2025-10-06 01:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('max_listings', models.IntegerField(help_text='Maximum number of active listings (-1 for unlimited)')),
                ('featured_listings', models.IntegerField(default=0, help_text='Number of featured listings allowed')),
                ('priority_support', models.BooleanField(default=False)),
                ('analytics_access', models.BooleanField(default=False)),
                ('verification_badge', models.BooleanField(default=False)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('service_roles', models.CharField(blank=True, default='general', help_text='Service roles (comma-separated): rider, restaurant_owner, etc.', max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('location', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('profile_visibility', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_in_app', models.BooleanField(default=True)),
                ('enable_sms', models.BooleanField(default=False)),
                ('enable_whatsapp', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('ride_notifications', models.BooleanField(default=True)),
                ('food_notifications', models.BooleanField(default=True)),
                ('shop_notifications', models.BooleanField(default=True)),
                ('pharmacy_notifications', models.BooleanField(default=True)),
                ('rental_notifications', models.BooleanField(default=True)),
                ('subscription_notifications', models.BooleanField(default=True)),
                ('promotional_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('subscribed', 'Subscribed'), ('renewed', 'Renewed'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('payment', 'Payment')], max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending Payment')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_listings_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='accounts.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ride_requested', 'Ride Requested'), ('ride_accepted', 'Ride Accepted'), ('ride_arrived', 'Driver Arrived'), ('ride_started', 'Ride Started'), ('ride_completed', 'Ride Completed'), ('ride_cancelled', 'Ride Cancelled'), ('food_order_placed', 'Food Order Placed'), ('food_order_confirmed', 'Food Order Confirmed'), ('food_preparing', 'Food Being Prepared'), ('food_ready', 'Food Ready for Pickup'), ('food_out_for_delivery', 'Food Out for Delivery'), ('food_delivered', 'Food Delivered'), ('shop_order_placed', 'Shop Order Placed'), ('shop_order_confirmed', 'Shop Order Confirmed'), ('shop_order_shipped', 'Shop Order Shipped'), ('shop_order_delivered', 'Shop Order Delivered'), ('pharmacy_order_placed', 'Pharmacy Order Placed'), ('pharmacy_order_confirmed', 'Pharmacy Order Confirmed'), ('pharmacy_order_ready', 'Pharmacy Order Ready'), ('pharmacy_order_delivered', 'Pharmacy Order Delivered'), ('rental_booked', 'Rental Booked'), ('rental_confirmed', 'Rental Confirmed'), ('rental_started', 'Rental Started'), ('rental_ended', 'Rental Ended'), ('rental_cancelled', 'Rental Cancelled'), ('subscription_created', 'Subscription Created'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expiring', 'Subscription Expiring Soon'), ('subscription_expired', 'Subscription Expired'), ('subscription_cancelled', 'Subscription Cancelled'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('message_received', 'New Message'), ('review_received', 'New Review')], max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='in_app', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('reference_id', models.CharField(blank=True, help_text='ID of related object (order, ride, etc.)', max_length=100)),
                ('reference_type', models.CharField(blank=True, help_text='Type of related object (Order, Ride, etc.)', max_length=50)),
                ('data', models.JSONField(blank=True, help_text='Additional data for the notification', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('message_sid', models.CharField(blank=True, help_text='Twilio message SID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_no_user_id_b37b35_idx'), models.Index(fields=['status', 'channel'], name='accounts_no_status_13928e_idx'), models.Index(fields=['notification_type'], name='accounts_no_notific_6d2f3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('landlord', 'Landlord - List Properties'), ('tenant', 'Tenant - Find Rentals'), ('equipment_owner', 'Equipment Owner - Rent Equipment'), ('equipment_renter', 'Equipment Renter - Rent Equipment'), ('seller', 'Seller - Sell Products'), ('buyer', 'Buyer - Buy Products'), ('pharmacy_owner', 'Pharmacy Owner - Sell Medicine'), ('patient', 'Patient - Buy Medicine'), ('restaurant_owner', 'Restaurant Owner - Sell Food'), ('customer', 'Customer - Order Food'), ('driver', 'Driver - Provide Rides'), ('rider', 'Rider - Book Rides'), ('general', 'General User')], max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Why do you want this role?')),
                ('experience', models.TextField(blank=True, help_text='Relevant experience or qualifications')),
                ('document', models.FileField(blank=True, help_text='Supporting document (license, certificate, etc.)', null=True, upload_to='role_applications/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text="Admin's review notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Application',
                'verbose_name_plural': 'Role Applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounts_ro_status_bc40b2_idx'), models.Index(fields=['user', 'status'], name='accounts_ro_user_id_e44c8e_idx')],
            },
        ),
    ]
