# Generated by Django 5.2.6 on 2025-10-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleapplication',
            name='role',
            field=models.CharField(choices=[('landlord', 'Landlord - List Properties'), ('equipment_owner', 'Equipment Owner - Rent Equipment'), ('seller', 'Seller - Sell Products'), ('pharmacy_owner', 'Pharmacy Owner - Sell Medicine'), ('restaurant_owner', 'Restaurant Owner - Sell Food'), ('driver', 'Driver - Provide Rides'), ('rider', 'Rider - Book Rides'), ('general', 'General User')], max_length=50),
        ),
    ]
