# Generated by Django 5.2.6 on 2025-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_roleapplication_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Direct profile picture URL from any image hosting service', max_length=500, null=True),
        ),
    ]
