# Generated by Django 4.2.26 on 2025-12-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_verificationcode_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='enable_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roleapplication',
            name='role',
            field=models.CharField(choices=[('landlord', 'Landlord - List Properties'), ('equipment_owner', 'Equipment Owner - Rent Equipment'), ('seller', 'Seller - Sell Products'), ('pharmacy_owner', 'Pharmacy Owner - Sell Medicine'), ('restaurant_owner', 'Restaurant Owner - Sell Food'), ('driver', 'Driver - Provide Rides'), ('rider', 'Rider - Book Rides'), ('delivery_driver', 'Delivery Driver - Express Deliveries'), ('general', 'General User')], max_length=50),
        ),
    ]
