# Generated by Django 4.2.26 on 2025-12-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_enable_sms_by_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
