# Generated by Django 4.2.26 on 2026-01-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_change_profile_picture_to_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleapplication',
            name='business_address',
            field=models.TextField(blank=True, help_text='Business address'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='business_email',
            field=models.EmailField(blank=True, help_text='Business email address', max_length=254),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='business_license',
            field=models.FileField(blank=True, help_text='Business license or registration certificate', null=True, upload_to='role_applications/licenses/'),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='business_name',
            field=models.CharField(blank=True, help_text='Name of your business', max_length=200),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='business_phone',
            field=models.CharField(blank=True, help_text='Business phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='business_type',
            field=models.CharField(blank=True, help_text='Type of business (e.g., Restaurant type, Shop category)', max_length=100),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='city',
            field=models.CharField(blank=True, help_text='City of operation', max_length=100),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='license_number',
            field=models.CharField(blank=True, help_text='Business license or registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='roleapplication',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True, help_text='Years of experience in this business', null=True),
        ),
    ]
