# Generated by Django 4.2.26 on 2026-01-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_roleapplication_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='URL to redirect when notification is clicked', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('ride_requested', 'Ride Requested'), ('ride_accepted', 'Ride Accepted'), ('ride_arrived', 'Driver Arrived'), ('ride_started', 'Ride Started'), ('ride_completed', 'Ride Completed'), ('ride_cancelled', 'Ride Cancelled'), ('food_order_placed', 'Food Order Placed'), ('food_order_confirmed', 'Food Order Confirmed'), ('food_preparing', 'Food Being Prepared'), ('food_ready', 'Food Ready for Pickup'), ('food_out_for_delivery', 'Food Out for Delivery'), ('food_delivered', 'Food Delivered'), ('shop_order_placed', 'Shop Order Placed'), ('shop_order_confirmed', 'Shop Order Confirmed'), ('shop_order_shipped', 'Shop Order Shipped'), ('shop_order_delivered', 'Shop Order Delivered'), ('pharmacy_order_placed', 'Pharmacy Order Placed'), ('pharmacy_order_confirmed', 'Pharmacy Order Confirmed'), ('pharmacy_order_ready', 'Pharmacy Order Ready'), ('pharmacy_order_delivered', 'Pharmacy Order Delivered'), ('rental_booked', 'Rental Booked'), ('rental_confirmed', 'Rental Confirmed'), ('rental_started', 'Rental Started'), ('rental_ended', 'Rental Ended'), ('rental_cancelled', 'Rental Cancelled'), ('subscription_created', 'Subscription Created'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expiring', 'Subscription Expiring Soon'), ('subscription_expired', 'Subscription Expired'), ('subscription_cancelled', 'Subscription Cancelled'), ('role_application_submitted', 'Role Application Submitted'), ('role_application_approved', 'Role Application Approved'), ('role_application_rejected', 'Role Application Rejected'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('message_received', 'New Message'), ('review_received', 'New Review')], max_length=50),
        ),
    ]
