# Generated by Django 5.2.6 on 2025-10-18 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('food', 'Food'), ('shop', 'Shop'), ('ride', 'Ride'), ('pharmacy', 'Pharmacy'), ('rent', 'Rent')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_message_at'],
                'indexes': [models.Index(fields=['user1', 'app_type'], name='messaging_c_user1_i_fbab5f_idx'), models.Index(fields=['user2', 'app_type'], name='messaging_c_user2_i_0fcece_idx'), models.Index(fields=['-last_message_at'], name='messaging_c_last_me_3f31f1_idx')],
                'unique_together': {('user1', 'user2', 'content_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_type', models.CharField(choices=[('food', 'Food'), ('shop', 'Shop'), ('ride', 'Ride'), ('pharmacy', 'Pharmacy'), ('rent', 'Rent')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/attachments/')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'app_type'], name='messaging_m_sender__78e982_idx'), models.Index(fields=['receiver', 'is_read'], name='messaging_m_receive_5b2f13_idx'), models.Index(fields=['content_type', 'object_id'], name='messaging_m_content_a355a9_idx')],
            },
        ),
    ]
