# Generated by Django 5.2.6 on 2025-10-20 08:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
