# Generated by Django 5.2.6 on 2025-10-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Pick Up Point'), ('door_delivery', 'Door Delivery')], default='door_delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash on Delivery'), ('online_payment', 'Online Payment')], default='online_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text="Google Drive image link. IMPORTANT: Set file sharing to 'Anyone with the link can view' in Google Drive", max_length=500),
        ),
    ]
