# Generated by Django 5.2.6 on 2025-10-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_productimage_image_productimage_image_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
