# Generated by Django 5.2.6 on 2025-10-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_image_url_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_file',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(default=1, help_text="Google Drive image link. IMPORTANT: Set file sharing to 'Anyone with the link can view' in Google Drive", max_length=500),
            preserve_default=False,
        ),
    ]
