# Generated by Django 5.2.6 on 2025-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_productimage_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.URLField(help_text='Direct image URL from any image hosting service (e.g., Imgur, Cloudinary, AWS S3, Google Drive, etc.)', max_length=500),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.URLField(help_text='Direct image URL from any image hosting service', max_length=500),
        ),
    ]
