# Generated by Django 4.2.26 on 2026-01-14 04:37

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_alter_category_description_alter_category_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='Shop logo image', null=True, upload_to='shops/logos/')),
                ('image', models.ImageField(blank=True, help_text='Main shop banner image', null=True, upload_to='shops/images/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for map location', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for map location', max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], default='active', max_length=25)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('business_type', models.CharField(blank=True, help_text='Type of business (e.g., Electronics, Fashion, Grocery)', max_length=100)),
                ('opening_hours', models.TextField(blank=True, help_text='Opening hours (e.g., "Mon-Fri: 9AM-6PM, Sat: 10AM-4PM")')),
                ('delivery_available', models.BooleanField(default=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_delivery_time', models.PositiveIntegerField(default=60, help_text='Estimated delivery time in minutes')),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Shop owner/manager', on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-is_featured', '-average_rating', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(blank=True, help_text='Shop this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['status', '-is_featured'], name='shop_shop_status_6a2ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['city', 'status'], name='shop_shop_city_a9da32_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['slug'], name='shop_shop_slug_3bbea9_idx'),
        ),
    ]
