"""
Management command to populate sample pharmacies and medicines
"""

from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from pharmacy.models import Pharmacy, Medicine, MedicineCategory
from decimal import Decimal
from datetime import date, timedelta

User = get_user_model()


class Command(BaseCommand):
    help = 'Populate sample pharmacies and medicines'

    def handle(self, *args, **options):
        self.stdout.write('Creating sample pharmacies and medicines...')
        
        # Get or create a default owner (first superuser or create one)
        owner = User.objects.filter(is_superuser=True).first()
        if not owner:
            owner = User.objects.first()
        
        if not owner:
            self.stdout.write(self.style.ERROR('No user found. Please create a user first.'))
            return

        # Create medicine categories
        categories_data = [
            {'name': 'Pain Relief', 'description': 'Medications for pain management'},
            {'name': 'Antibiotics', 'description': 'Medications to treat bacterial infections'},
            {'name': 'Vitamins & Supplements', 'description': 'Nutritional supplements and vitamins'},
            {'name': 'Cold & Flu', 'description': 'Medications for cold and flu symptoms'},
            {'name': 'Digestive Health', 'description': 'Medications for digestive issues'},
            {'name': 'Skin Care', 'description': 'Topical medications and skin treatments'},
            {'name': 'Diabetes Care', 'description': 'Medications for diabetes management'},
            {'name': 'Heart Health', 'description': 'Cardiovascular medications'},
        ]
        
        categories = {}
        for cat_data in categories_data:
            category, created = MedicineCategory.objects.get_or_create(
                name=cat_data['name'],
                defaults={'description': cat_data['description']}
            )
            categories[cat_data['name']] = category
            if created:
                self.stdout.write(f'  Created category: {category.name}')

        # Pharmacy data
        pharmacies_data = [
            {
                'name': 'HealthPlus Pharmacy',
                'description': 'Your trusted neighborhood pharmacy offering quality medicines, health products, and professional pharmaceutical care. We provide personalized service and expert advice for all your health needs.',
                'phone': '+233 24 123 4567',
                'email': 'info@healthplusgh.com',
                'address': '15 Oxford Street, Osu',
                'city': 'Accra',
                'state': 'Greater Accra',
                'license_number': 'GPC-2024-001',
                'is_24_hours': True,
                'is_verified': True,
                'is_featured': True,
                'delivery_fee': Decimal('10.00'),
                'estimated_delivery_time': 45,
                'average_rating': Decimal('4.8'),
            },
            {
                'name': 'MediCare Pharmacy',
                'description': 'A modern pharmacy chain committed to providing affordable healthcare solutions. We stock a wide range of prescription and over-the-counter medications with competitive pricing.',
                'phone': '+233 30 234 5678',
                'email': 'contact@medicaregh.com',
                'address': '25 Ring Road Central',
                'city': 'Accra',
                'state': 'Greater Accra',
                'license_number': 'GPC-2024-002',
                'is_24_hours': False,
                'is_verified': True,
                'is_featured': True,
                'delivery_fee': Decimal('8.00'),
                'estimated_delivery_time': 60,
                'average_rating': Decimal('4.5'),
                'opening_hours': 'Mon-Fri: 8AM-9PM\nSat: 9AM-6PM\nSun: 10AM-4PM',
            },
            {
                'name': 'PharmaSave Ghana',
                'description': 'Leading pharmacy offering premium healthcare products and services. Our trained pharmacists are available to provide expert consultations and medication management.',
                'phone': '+233 54 345 6789',
                'email': 'hello@pharmasavegh.com',
                'address': '10 Asafo Market Road',
                'city': 'Kumasi',
                'state': 'Ashanti',
                'license_number': 'GPC-2024-003',
                'is_24_hours': False,
                'is_verified': True,
                'is_featured': False,
                'delivery_fee': Decimal('12.00'),
                'estimated_delivery_time': 50,
                'average_rating': Decimal('4.6'),
                'opening_hours': 'Mon-Sat: 7AM-10PM\nSun: 9AM-6PM',
            },
            {
                'name': 'City Pharmacy',
                'description': 'Conveniently located in the heart of Takoradi, City Pharmacy provides quick access to essential medications and health products. We prioritize customer satisfaction and quality care.',
                'phone': '+233 31 456 7890',
                'email': 'info@citypharmacy.gh',
                'address': '5 Market Circle',
                'city': 'Takoradi',
                'state': 'Western',
                'license_number': 'GPC-2024-004',
                'is_24_hours': True,
                'is_verified': True,
                'is_featured': False,
                'delivery_fee': Decimal('15.00'),
                'estimated_delivery_time': 40,
                'average_rating': Decimal('4.3'),
            },
            {
                'name': 'Wellness Pharmacy',
                'description': 'Focused on holistic health and wellness, we offer both traditional medications and natural health products. Our pharmacists specialize in lifestyle medicine and preventive care.',
                'phone': '+233 26 567 8901',
                'email': 'care@wellnesspharmacy.gh',
                'address': '33 Independence Avenue',
                'city': 'Tema',
                'state': 'Greater Accra',
                'license_number': 'GPC-2024-005',
                'is_24_hours': False,
                'is_verified': True,
                'is_featured': True,
                'delivery_fee': Decimal('10.00'),
                'estimated_delivery_time': 55,
                'average_rating': Decimal('4.7'),
                'opening_hours': 'Mon-Fri: 7AM-9PM\nSat-Sun: 8AM-8PM',
            },
        ]

        # Medicines data per pharmacy
        medicines_data = [
            # Pharmacy 1 - HealthPlus Pharmacy
            [
                {
                    'name': 'Paracetamol 500mg',
                    'generic_name': 'Paracetamol',
                    'brand_name': 'Panadol',
                    'category': 'Pain Relief',
                    'description': 'Effective pain reliever and fever reducer. Suitable for headaches, muscle aches, and minor pain.',
                    'usage': 'Take 1-2 tablets every 4-6 hours as needed. Do not exceed 8 tablets in 24 hours.',
                    'dosage': '500mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Paracetamol 500mg',
                    'side_effects': 'Rare: allergic reactions, skin rash',
                    'price': Decimal('15.00'),
                    'stock_quantity': 500,
                    'manufacturer': 'GlaxoSmithKline',
                    'pack_size': '24 tablets',
                    'requires_prescription': False,
                    'is_featured': True,
                },
                {
                    'name': 'Amoxicillin 500mg',
                    'generic_name': 'Amoxicillin',
                    'brand_name': 'Amoxil',
                    'category': 'Antibiotics',
                    'description': 'Broad-spectrum antibiotic for treating bacterial infections including respiratory and urinary tract infections.',
                    'usage': 'Take 1 capsule three times daily for 7-10 days or as prescribed.',
                    'dosage': '500mg',
                    'dosage_form': 'capsule',
                    'active_ingredients': 'Amoxicillin trihydrate 500mg',
                    'side_effects': 'Nausea, diarrhea, allergic reactions',
                    'price': Decimal('35.00'),
                    'stock_quantity': 200,
                    'manufacturer': 'Pfizer',
                    'pack_size': '21 capsules',
                    'requires_prescription': True,
                    'is_featured': True,
                },
                {
                    'name': 'Vitamin C 1000mg',
                    'generic_name': 'Ascorbic Acid',
                    'brand_name': 'Cevit',
                    'category': 'Vitamins & Supplements',
                    'description': 'High-potency vitamin C supplement for immune support and antioxidant protection.',
                    'usage': 'Take 1 tablet daily with food.',
                    'dosage': '1000mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Ascorbic Acid 1000mg',
                    'side_effects': 'May cause stomach upset in high doses',
                    'price': Decimal('45.00'),
                    'stock_quantity': 300,
                    'manufacturer': 'Nature Made',
                    'pack_size': '60 tablets',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Omeprazole 20mg',
                    'generic_name': 'Omeprazole',
                    'brand_name': 'Prilosec',
                    'category': 'Digestive Health',
                    'description': 'Proton pump inhibitor for treating heartburn, acid reflux, and stomach ulcers.',
                    'usage': 'Take 1 capsule daily before breakfast for 14-28 days.',
                    'dosage': '20mg',
                    'dosage_form': 'capsule',
                    'active_ingredients': 'Omeprazole 20mg',
                    'side_effects': 'Headache, nausea, diarrhea',
                    'price': Decimal('28.00'),
                    'stock_quantity': 150,
                    'manufacturer': 'AstraZeneca',
                    'pack_size': '28 capsules',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Cetirizine 10mg',
                    'generic_name': 'Cetirizine',
                    'brand_name': 'Zyrtec',
                    'category': 'Cold & Flu',
                    'description': 'Non-drowsy antihistamine for relief from allergy symptoms including sneezing, runny nose, and itchy eyes.',
                    'usage': 'Take 1 tablet once daily.',
                    'dosage': '10mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Cetirizine hydrochloride 10mg',
                    'side_effects': 'Mild drowsiness, dry mouth',
                    'price': Decimal('22.00'),
                    'stock_quantity': 250,
                    'manufacturer': 'Johnson & Johnson',
                    'pack_size': '30 tablets',
                    'requires_prescription': False,
                    'is_featured': True,
                },
            ],
            # Pharmacy 2 - MediCare Pharmacy
            [
                {
                    'name': 'Ibuprofen 400mg',
                    'generic_name': 'Ibuprofen',
                    'brand_name': 'Advil',
                    'category': 'Pain Relief',
                    'description': 'Anti-inflammatory pain reliever for headaches, muscle pain, arthritis, and menstrual cramps.',
                    'usage': 'Take 1 tablet every 4-6 hours with food. Maximum 3 tablets daily.',
                    'dosage': '400mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Ibuprofen 400mg',
                    'side_effects': 'Stomach upset, nausea, dizziness',
                    'price': Decimal('18.00'),
                    'stock_quantity': 400,
                    'manufacturer': 'Pfizer',
                    'pack_size': '20 tablets',
                    'requires_prescription': False,
                    'is_featured': True,
                },
                {
                    'name': 'Metformin 500mg',
                    'generic_name': 'Metformin',
                    'brand_name': 'Glucophage',
                    'category': 'Diabetes Care',
                    'description': 'First-line medication for type 2 diabetes, helps control blood sugar levels.',
                    'usage': 'Take as prescribed by doctor, usually 1-2 tablets with meals.',
                    'dosage': '500mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Metformin hydrochloride 500mg',
                    'side_effects': 'Nausea, diarrhea, stomach discomfort',
                    'price': Decimal('32.00'),
                    'stock_quantity': 300,
                    'manufacturer': 'Merck',
                    'pack_size': '60 tablets',
                    'requires_prescription': True,
                    'is_featured': True,
                },
                {
                    'name': 'Multivitamin Plus',
                    'generic_name': 'Multivitamin Complex',
                    'brand_name': 'Centrum',
                    'category': 'Vitamins & Supplements',
                    'description': 'Complete daily multivitamin with essential vitamins and minerals for overall health.',
                    'usage': 'Take 1 tablet daily with breakfast.',
                    'dosage': 'Standard',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Vitamins A, B, C, D, E, K, Iron, Zinc, Calcium',
                    'side_effects': 'Usually well tolerated',
                    'price': Decimal('55.00'),
                    'stock_quantity': 200,
                    'manufacturer': 'Pfizer',
                    'pack_size': '90 tablets',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Hydrocortisone Cream 1%',
                    'generic_name': 'Hydrocortisone',
                    'brand_name': 'Cortaid',
                    'category': 'Skin Care',
                    'description': 'Topical corticosteroid for relief from skin irritation, itching, and inflammation.',
                    'usage': 'Apply thin layer to affected area 2-3 times daily.',
                    'dosage': '1%',
                    'dosage_form': 'cream',
                    'active_ingredients': 'Hydrocortisone 1%',
                    'side_effects': 'Skin thinning with prolonged use',
                    'price': Decimal('25.00'),
                    'stock_quantity': 100,
                    'manufacturer': 'Johnson & Johnson',
                    'pack_size': '30g tube',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Cold & Flu Relief',
                    'generic_name': 'Paracetamol/Phenylephrine',
                    'brand_name': 'Lemsip',
                    'category': 'Cold & Flu',
                    'description': 'Hot lemon drink for cold and flu symptoms including headache, fever, and congestion.',
                    'usage': 'Dissolve 1 sachet in hot water every 4-6 hours. Maximum 4 sachets daily.',
                    'dosage': '650mg/10mg',
                    'dosage_form': 'powder',
                    'active_ingredients': 'Paracetamol 650mg, Phenylephrine 10mg',
                    'side_effects': 'May cause drowsiness',
                    'price': Decimal('20.00'),
                    'stock_quantity': 180,
                    'manufacturer': 'Reckitt Benckiser',
                    'pack_size': '10 sachets',
                    'requires_prescription': False,
                    'is_featured': True,
                },
            ],
            # Pharmacy 3 - PharmaSave Ghana
            [
                {
                    'name': 'Aspirin 100mg',
                    'generic_name': 'Acetylsalicylic Acid',
                    'brand_name': 'Bayer Aspirin',
                    'category': 'Heart Health',
                    'description': 'Low-dose aspirin for heart health and prevention of blood clots.',
                    'usage': 'Take 1 tablet daily with food as prescribed.',
                    'dosage': '100mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Acetylsalicylic Acid 100mg',
                    'side_effects': 'Stomach irritation, bleeding risk',
                    'price': Decimal('12.00'),
                    'stock_quantity': 600,
                    'manufacturer': 'Bayer',
                    'pack_size': '100 tablets',
                    'requires_prescription': False,
                    'is_featured': True,
                },
                {
                    'name': 'Ciprofloxacin 500mg',
                    'generic_name': 'Ciprofloxacin',
                    'brand_name': 'Cipro',
                    'category': 'Antibiotics',
                    'description': 'Fluoroquinolone antibiotic for serious bacterial infections.',
                    'usage': 'Take 1 tablet twice daily for 7-14 days as prescribed.',
                    'dosage': '500mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Ciprofloxacin hydrochloride 500mg',
                    'side_effects': 'Nausea, headache, tendon problems',
                    'price': Decimal('42.00'),
                    'stock_quantity': 100,
                    'manufacturer': 'Bayer',
                    'pack_size': '14 tablets',
                    'requires_prescription': True,
                    'is_featured': False,
                },
                {
                    'name': 'Omega-3 Fish Oil',
                    'generic_name': 'Fish Oil',
                    'brand_name': 'Nature\'s Bounty',
                    'category': 'Vitamins & Supplements',
                    'description': 'High-quality fish oil supplement for heart and brain health.',
                    'usage': 'Take 2 softgels daily with food.',
                    'dosage': '1000mg',
                    'dosage_form': 'capsule',
                    'active_ingredients': 'Fish Oil 1000mg (EPA 180mg, DHA 120mg)',
                    'side_effects': 'Fishy aftertaste, mild stomach upset',
                    'price': Decimal('65.00'),
                    'stock_quantity': 150,
                    'manufacturer': 'Nature\'s Bounty',
                    'pack_size': '120 softgels',
                    'requires_prescription': False,
                    'is_featured': True,
                },
                {
                    'name': 'Antacid Suspension',
                    'generic_name': 'Aluminum/Magnesium Hydroxide',
                    'brand_name': 'Maalox',
                    'category': 'Digestive Health',
                    'description': 'Fast-acting liquid antacid for heartburn and indigestion relief.',
                    'usage': 'Take 10-20ml as needed, up to 4 times daily.',
                    'dosage': '400mg/400mg per 10ml',
                    'dosage_form': 'syrup',
                    'active_ingredients': 'Aluminum hydroxide, Magnesium hydroxide',
                    'side_effects': 'Constipation or diarrhea',
                    'price': Decimal('30.00'),
                    'stock_quantity': 120,
                    'manufacturer': 'Sanofi',
                    'pack_size': '200ml bottle',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Cough Syrup',
                    'generic_name': 'Dextromethorphan/Guaifenesin',
                    'brand_name': 'Robitussin',
                    'category': 'Cold & Flu',
                    'description': 'Expectorant and cough suppressant for productive and dry coughs.',
                    'usage': 'Take 10ml every 4 hours. Maximum 6 doses daily.',
                    'dosage': '15mg/100mg per 5ml',
                    'dosage_form': 'syrup',
                    'active_ingredients': 'Dextromethorphan 15mg, Guaifenesin 100mg',
                    'side_effects': 'Drowsiness, nausea',
                    'price': Decimal('28.00'),
                    'stock_quantity': 200,
                    'manufacturer': 'Pfizer',
                    'pack_size': '100ml bottle',
                    'requires_prescription': False,
                    'is_featured': False,
                },
            ],
            # Pharmacy 4 - City Pharmacy
            [
                {
                    'name': 'Diclofenac Gel 1%',
                    'generic_name': 'Diclofenac',
                    'brand_name': 'Voltaren',
                    'category': 'Pain Relief',
                    'description': 'Topical anti-inflammatory gel for muscle and joint pain.',
                    'usage': 'Apply to affected area 3-4 times daily. Massage gently.',
                    'dosage': '1%',
                    'dosage_form': 'cream',
                    'active_ingredients': 'Diclofenac diethylamine 1.16%',
                    'side_effects': 'Skin irritation, rash',
                    'price': Decimal('38.00'),
                    'stock_quantity': 80,
                    'manufacturer': 'Novartis',
                    'pack_size': '50g tube',
                    'requires_prescription': False,
                    'is_featured': True,
                },
                {
                    'name': 'Lisinopril 10mg',
                    'generic_name': 'Lisinopril',
                    'brand_name': 'Zestril',
                    'category': 'Heart Health',
                    'description': 'ACE inhibitor for treating high blood pressure and heart failure.',
                    'usage': 'Take 1 tablet daily as prescribed by doctor.',
                    'dosage': '10mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Lisinopril 10mg',
                    'side_effects': 'Dry cough, dizziness, headache',
                    'price': Decimal('48.00'),
                    'stock_quantity': 200,
                    'manufacturer': 'AstraZeneca',
                    'pack_size': '30 tablets',
                    'requires_prescription': True,
                    'is_featured': True,
                },
                {
                    'name': 'Vitamin D3 5000IU',
                    'generic_name': 'Cholecalciferol',
                    'brand_name': 'Now Foods',
                    'category': 'Vitamins & Supplements',
                    'description': 'High-potency vitamin D3 for bone health and immune support.',
                    'usage': 'Take 1 softgel daily with food.',
                    'dosage': '5000IU',
                    'dosage_form': 'capsule',
                    'active_ingredients': 'Vitamin D3 (Cholecalciferol) 5000IU',
                    'side_effects': 'Rare at recommended doses',
                    'price': Decimal('40.00'),
                    'stock_quantity': 180,
                    'manufacturer': 'Now Foods',
                    'pack_size': '120 softgels',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Loperamide 2mg',
                    'generic_name': 'Loperamide',
                    'brand_name': 'Imodium',
                    'category': 'Digestive Health',
                    'description': 'Fast relief from diarrhea symptoms.',
                    'usage': 'Take 2 capsules initially, then 1 after each loose stool. Maximum 8 daily.',
                    'dosage': '2mg',
                    'dosage_form': 'capsule',
                    'active_ingredients': 'Loperamide hydrochloride 2mg',
                    'side_effects': 'Constipation, stomach cramps',
                    'price': Decimal('15.00'),
                    'stock_quantity': 250,
                    'manufacturer': 'Johnson & Johnson',
                    'pack_size': '12 capsules',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Insulin Glargine',
                    'generic_name': 'Insulin Glargine',
                    'brand_name': 'Lantus',
                    'category': 'Diabetes Care',
                    'description': 'Long-acting insulin for blood sugar control in diabetes.',
                    'usage': 'Inject once daily at the same time as prescribed.',
                    'dosage': '100 units/ml',
                    'dosage_form': 'injection',
                    'active_ingredients': 'Insulin glargine 100 units/ml',
                    'side_effects': 'Low blood sugar, injection site reactions',
                    'price': Decimal('180.00'),
                    'stock_quantity': 50,
                    'manufacturer': 'Sanofi',
                    'pack_size': '3ml cartridge',
                    'requires_prescription': True,
                    'is_featured': True,
                },
            ],
            # Pharmacy 5 - Wellness Pharmacy
            [
                {
                    'name': 'Tramadol 50mg',
                    'generic_name': 'Tramadol',
                    'brand_name': 'Ultram',
                    'category': 'Pain Relief',
                    'description': 'Prescription pain reliever for moderate to severe pain.',
                    'usage': 'Take 1-2 tablets every 4-6 hours as needed. Maximum 400mg daily.',
                    'dosage': '50mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Tramadol hydrochloride 50mg',
                    'side_effects': 'Dizziness, nausea, constipation, drowsiness',
                    'price': Decimal('55.00'),
                    'stock_quantity': 100,
                    'manufacturer': 'Janssen',
                    'pack_size': '30 tablets',
                    'requires_prescription': True,
                    'is_featured': False,
                },
                {
                    'name': 'Amlodipine 5mg',
                    'generic_name': 'Amlodipine',
                    'brand_name': 'Norvasc',
                    'category': 'Heart Health',
                    'description': 'Calcium channel blocker for high blood pressure and chest pain.',
                    'usage': 'Take 1 tablet once daily.',
                    'dosage': '5mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Amlodipine besylate 5mg',
                    'side_effects': 'Swelling, fatigue, dizziness',
                    'price': Decimal('35.00'),
                    'stock_quantity': 300,
                    'manufacturer': 'Pfizer',
                    'pack_size': '30 tablets',
                    'requires_prescription': True,
                    'is_featured': True,
                },
                {
                    'name': 'Probiotic Complex',
                    'generic_name': 'Lactobacillus/Bifidobacterium',
                    'brand_name': 'Culturelle',
                    'category': 'Digestive Health',
                    'description': 'Daily probiotic for digestive and immune health.',
                    'usage': 'Take 1 capsule daily with or without food.',
                    'dosage': '10 billion CFU',
                    'dosage_form': 'capsule',
                    'active_ingredients': 'Lactobacillus rhamnosus GG 10 billion CFU',
                    'side_effects': 'Mild bloating initially',
                    'price': Decimal('50.00'),
                    'stock_quantity': 120,
                    'manufacturer': 'i-Health',
                    'pack_size': '30 capsules',
                    'requires_prescription': False,
                    'is_featured': True,
                },
                {
                    'name': 'Clotrimazole Cream 1%',
                    'generic_name': 'Clotrimazole',
                    'brand_name': 'Canesten',
                    'category': 'Skin Care',
                    'description': 'Antifungal cream for athlete\'s foot, ringworm, and yeast infections.',
                    'usage': 'Apply thin layer to affected area 2-3 times daily for 2-4 weeks.',
                    'dosage': '1%',
                    'dosage_form': 'cream',
                    'active_ingredients': 'Clotrimazole 1%',
                    'side_effects': 'Mild irritation, burning sensation',
                    'price': Decimal('22.00'),
                    'stock_quantity': 90,
                    'manufacturer': 'Bayer',
                    'pack_size': '20g tube',
                    'requires_prescription': False,
                    'is_featured': False,
                },
                {
                    'name': 'Loratadine 10mg',
                    'generic_name': 'Loratadine',
                    'brand_name': 'Claritin',
                    'category': 'Cold & Flu',
                    'description': 'Non-drowsy antihistamine for allergy relief.',
                    'usage': 'Take 1 tablet once daily.',
                    'dosage': '10mg',
                    'dosage_form': 'tablet',
                    'active_ingredients': 'Loratadine 10mg',
                    'side_effects': 'Headache, dry mouth (rare)',
                    'price': Decimal('25.00'),
                    'stock_quantity': 200,
                    'manufacturer': 'Bayer',
                    'pack_size': '30 tablets',
                    'requires_prescription': False,
                    'is_featured': False,
                },
            ],
        ]

        # Create pharmacies and their medicines
        for i, pharmacy_data in enumerate(pharmacies_data):
            pharmacy, created = Pharmacy.objects.get_or_create(
                license_number=pharmacy_data['license_number'],
                defaults={
                    'owner': owner,
                    'name': pharmacy_data['name'],
                    'description': pharmacy_data['description'],
                    'phone': pharmacy_data['phone'],
                    'email': pharmacy_data['email'],
                    'address': pharmacy_data['address'],
                    'city': pharmacy_data['city'],
                    'state': pharmacy_data['state'],
                    'is_24_hours': pharmacy_data.get('is_24_hours', False),
                    'is_verified': pharmacy_data.get('is_verified', True),
                    'is_featured': pharmacy_data.get('is_featured', False),
                    'delivery_fee': pharmacy_data.get('delivery_fee', Decimal('10.00')),
                    'estimated_delivery_time': pharmacy_data.get('estimated_delivery_time', 60),
                    'average_rating': pharmacy_data.get('average_rating', Decimal('4.0')),
                    'opening_hours': pharmacy_data.get('opening_hours', ''),
                    'status': 'active',
                    'delivery_available': True,
                }
            )
            
            if created:
                self.stdout.write(f'Created pharmacy: {pharmacy.name}')
            else:
                self.stdout.write(f'Pharmacy already exists: {pharmacy.name}')

            # Create medicines for this pharmacy
            for med_data in medicines_data[i]:
                category = categories.get(med_data['category'])
                if not category:
                    self.stdout.write(self.style.WARNING(f"Category not found: {med_data['category']}"))
                    continue

                medicine, med_created = Medicine.objects.get_or_create(
                    name=med_data['name'],
                    pharmacy=pharmacy,
                    defaults={
                        'owner': owner,
                        'generic_name': med_data['generic_name'],
                        'brand_name': med_data['brand_name'],
                        'category': category,
                        'description': med_data['description'],
                        'usage': med_data['usage'],
                        'dosage': med_data['dosage'],
                        'dosage_form': med_data['dosage_form'],
                        'active_ingredients': med_data['active_ingredients'],
                        'side_effects': med_data.get('side_effects', ''),
                        'price': med_data['price'],
                        'stock_quantity': med_data['stock_quantity'],
                        'manufacturer': med_data['manufacturer'],
                        'pack_size': med_data.get('pack_size', ''),
                        'requires_prescription': med_data.get('requires_prescription', False),
                        'is_featured': med_data.get('is_featured', False),
                        'is_active': True,
                        'expiry_date': date.today() + timedelta(days=365),
                    }
                )
                
                if med_created:
                    self.stdout.write(f'  - Created medicine: {medicine.name}')

        self.stdout.write(self.style.SUCCESS('\nSuccessfully populated pharmacies and medicines!'))
        self.stdout.write(f'Total pharmacies: {Pharmacy.objects.count()}')
        self.stdout.write(f'Total medicines: {Medicine.objects.count()}')
