# Generated by Django 5.2.6 on 2025-10-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_order_delivery_method_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.URLField(blank=True, help_text='Main restaurant image. Google Drive link or regular URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.URLField(blank=True, help_text="Google Drive image link or regular URL. For Google Drive: Set file sharing to 'Anyone with the link can view'", max_length=500, null=True),
        ),
    ]
