# Generated by Django 5.2.6 on 2025-10-23 17:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_restaurant_banner_image_restaurant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(blank=True, help_text='Type of cuisine (e.g., Italian, Chinese, Mexican)', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.TextField(blank=True, help_text='Opening hours text (e.g., "Mon-Fri: 9AM-10PM, Sat-Sun: 10AM-11PM")'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
