# Generated by Django 5.2.6 on 2025-10-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_restaurant_cuisine_type_restaurant_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='icon',
            field=models.URLField(blank=True, help_text='Direct icon URL from any image hosting service', max_length=500, null=True),
        ),
    ]
