# Generated by Django 4.2.26 on 2025-12-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_menuitem_description_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (alternative to uploaded image)', max_length=500, null=True),
        ),
    ]
