# Generated by Django 4.2.26 on 2025-12-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_menuitem_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Menu item image (supports both file uploads and URLs)', null=True, upload_to='menu_items/'),
        ),
    ]
